### ISSUE TITLE
how to fill an array with data?

### ISSUE THREAD

**Issue by Zodys** [issuimo/UnityResolve.hpp#13]
const auto assembly = UnityResolve::Get("assembly.dll | 程序集名称.dll");
const auto pClass   = assembly->Get("className | 类名称");
const auto array    = UnityResolve::UnityType::Array<T>::New(pClass, size);
std::vector<T> cppVector = array.ToVector();

how to fill an array with int, float, string, object, etc. values?

**Comment by issuimo** [comment]
use
array->Fill(value)
array[index] = value
