### ISSUE TITLE
How to create an instance and call a method?

### ISSUE THREAD

**Issue by ballsofsoul** [issuimo/UnityResolve.hpp#14]
For example, we have a `DirectoryInfo` class in mscorlib, which methods take an its instance as first argument, which in-game being created using .ctor method and passing in it the needed path for later usage.

`GetFiles`, for example:

![image](https://github.com/issuimo/UnityResolve.hpp/assets/170081532/5ca05ec3-4c2a-495e-a097-b8a9261cab17)

How to process that using UnityResolve?

**Comment by issuimo** [comment]
UnityResolveClass* pClass;
DirectoryInfo* ptr =  pClass->New<DirectoryInfo*>();
ptr->GetFiles(...)

**Comment by issuimo** [comment]
UnityResolve::Class* pClass;
UnityResolve::Method* ptr = pClass->Get<UnityResolve::Class>("GetFiles");
ptr->Invoke<ReturnType*>(instance, UnityResolve::UnityType::String::New("file"), 0);

**Comment by ballsofsoul** [comment]
> UnityResolveClass* pClass; DirectoryInfo* ptr = pClass->New<DirectoryInfo*>(); ptr->GetFiles(...)

Assuming i have implemented DirectoryInfo type?

> UnityResolve::Method* ptr = pClass->GetUnityResolve::Class("GetFiles");

You meant UnityResolve::Method* ptr = pClass->Get<UnityResolve::Method>("GetFiles");?

**Comment by issuimo** [comment]
yeah
