### ISSUE TITLE
#ASK

### ISSUE THREAD

**Issue by IkuzaDev** [issuimo/UnityResolve.hpp#15]
in dump.cs:
public class SystemData // TypeDefIndex: 6327
{ 
  public static bool bIsHookProtect; // 0x1020 field
  public static bool GetIsFirstLogin() { } //method
}

in main.cpp:
const auto assembly = UnityResolve::Get("Assembly-CSharp.dll");
const auto SystemData = assembly->Get("SystemData");
const auto bIsHookProtect = SystemData->Get<UnityResolve::Field>("bIsHookProtect");
const auto GetIsFirstLogin = SystemData->Get<UnityResolve::Method>("GetIsFirstLogin");
auto disable = false;
bIsHookProtect->SetValue(&disable);
GetIsFirstLogin->Invoke<bool>(true);

am I right?

**Comment by issuimo** [comment]
Yes, you are right.
