### ISSUE TITLE
ANDROID MODE ERROR

### ISSUE THREAD

**Issue by JoelitonMods** [issuimo/UnityResolve.hpp#2]
Android mode, many errors could help?

![photo_2024-01-24_09-23-45](https://github.com/issuimo/UnityResolve.hpp/assets/90171592/19a036f5-bb5e-41b3-84f6-42604a2010f6)

**Comment by JoelitonMods** [comment]
It has greatly reduced errors and now only has these

![photo_2024-01-24_11-24-52](https://github.com/issuimo/UnityResolve.hpp/assets/90171592/7824cfde-8b9f-4dc0-9cb6-7c07b629069e)

**Comment by JoelitonMods** [comment]
![photo_2024-01-24_11-43-26](https://github.com/issuimo/UnityResolve.hpp/assets/90171592/0618e375-9e72-46e8-8fb7-70d68a574db2)

**Comment by JoelitonMods** [comment]
errors resolved thank you

**Comment by JoelitonMods** [comment]
erros resolvidos obrigado

**Comment by TherCN** [comment]
> 解决错误

Hello, may I ask which compilation options you added to solve this error?
