### ISSUE TITLE
DumpToFile does not write data to a file

### ISSUE THREAD

**Issue by 1000blxdesss** [issuimo/UnityResolve.hpp#23]
I used the unityresolve file from the phasmophobia project, because the file from the main project is erroneous, when using the following lines, the code does not perform its function but simply creates empty files
```C++
UnityResolve::Init(GetModuleHandleA("GameAssembly.dll"), UnityResolve::Mode::Il2Cpp);

   UnityResolve::DumpToFile("C:/Users/hz/somethinggg/"); 
```

**Comment by RiritoNinigaya** [comment]
Me Too!!!
