### ISSUE TITLE
[inquiry] installation and execution inquiries

### ISSUE THREAD

**Issue by daeinlee** [issuimo/UnityResolve.hpp#6]
Hello. 
I don’t know anything about C++, so could you guide me on where and how to run it?
I don't know how to run it based on the explanation in the text alone.

**Comment by RiritoNinigaya** [comment]
Install Visual Studio 2022 Pro IDE

**Comment by RiritoNinigaya** [comment]
and this is header

**Comment by daeinlee** [comment]
> and this is header

Thank you so much for your reply.
Actually, I don't really understand because I have no experience with VS projects like this.
First, let's try it with the help of AI.

**Comment by RiritoNinigaya** [comment]
> > and this is header
> 
> Thank you so much for your reply. Actually, I don't really understand because I have no experience with VS projects like this. First, let's try it with the help of AI.

it is not helped, you can also try watch this repository as example and created another cheat for Unity Game(As Holoearth, Battletech, Muse Dash, Ancient Warfare 3, Town of Salem 2, etc): [LINK](https://github.com/issuimo/PhasmophobiaCheat/tree/main)

**Comment by daeinlee** [comment]
> > > 그리고 이건 헤더야
> > 
> > 
> > 답장을 보내 주셔서 감사합니다. 사실 저는 이런 VS 프로젝트를 해본 경험이 없어서 잘 이해가 되지 않습니다. 먼저 AI의 도움을 받아 시도해 보겠습니다.
> 
> 도움이 되지 않습니다. 예를 들어 이 저장소를 시청하고 Unity 게임에 대한 또 다른 치트를 만들 수도 있습니다(Holoearth, Battletech, Muse Dash, Ancient Warfare 3, Town of Salem 2 등): [LINK](https://github.com/issuimo/PhasmophobiaCheat/tree/main)

Thank you so much for the information. I've only used mobile devices, so it's still difficult to understand how to run it. Looking at the data, it seems like they create a menu and hook it, but I don't understand because I've only used it on mobile, and I can't start again because of work.

**Comment by RiritoNinigaya** [comment]
> > > > 그리고 이건 헤더야
> > > 
> > > 
> > > 답장을 보내 주셔서 감사합니다. 사실 저는 이런 VS 프로젝트를 해본 경험이 없어서 잘 이해가 되지 않습니다. 먼저 AI의 도움을 받아 시도해 보겠습니다.
> > 
> > 
> > 도움이 되지 않습니다. 예를 들어 이 저장소를 시청하고 Unity 게임에 대한 또 다른 치트를 만들 수도 있습니다(Holoearth, Battletech, Muse Dash, Ancient Warfare 3, Town of Salem 2 등): [LINK](https://github.com/issuimo/PhasmophobiaCheat/tree/main)
> 
> Thank you so much for the information. I've only used mobile devices, so it's still difficult to understand how to run it. Looking at the data, it seems like they create a menu and hook it, but I don't understand because I've only used it on mobile, and I can't start again because of work.

always welcome, you need PC for work!!!
