### ISSUE TITLE
error on android device

### ISSUE THREAD

**Issue by CubanGames01** [issuimo/UnityResolve.hpp#8]
There was no error in the compilation but when opening the game it closes, game used: Subway Surfers V_3.26.1

**Comment by issuimo** [comment]
Can you provide some call stack information?
Is this game Mono or il2cpp type?
Please provide more information.

**Comment by CubanGames01** [comment]
> ###
> [19 de março de 2024](#issuecomment-2005765745) yes it is il2cpp here is the game link: https://apkcombo.com/pt/subway-surfers/com.kiloo.subwaysurf/download/apk

**Comment by CubanGames01** [comment]
> Você pode fornecer algumas informações sobre a pilha de chamadas? Este jogo é do tipo Mono ou il2cpp? Forneça mais informações.

yes it is il2cpp here is the game link: https://apkcombo.com/pt/subway-surfers/com.kiloo.subwaysurf/download/apk

**Comment by CubanGames01** [comment]
> > > Você pode fornecer algumas informações sobre a pilha de chamadas? Este jogo é do tipo Mono ou il2cpp? Forneça mais informações.
> > 
> > 
> > sim, é il2cpp aqui está o link do jogo: https://apkcombo.com/pt/subway-surfers/com.kiloo.subwaysurf/download/apk
> 
> Ótimo, agora que sabemos o tipo de jogo. Porém, apenas conhecer o tipo de jogo não é suficiente para identificar o problema. IDA mostra que a tabela de exportação exporta todas as funções necessárias; esta parte da questão foi descartada. Agora precisamos determinar quaisquer problemas relacionados ao código, como inicialização.

I initialized it like this, after il2cpp started the game closed

![image](https://github.com/issuimo/UnityResolve.hpp/assets/163964035/2ecb98a8-d290-4bb4-a778-317bad6c9ecb)

**Comment by issuimo** [comment]
> > > > Você pode fornecer algumas informações sobre a pilha de chamadas? Este jogo é do tipo Mono ou il2cpp? Forneça mais informações.
> > > 
> > > 
> > > sim, é il2cpp aqui está o link do jogo: https://apkcombo.com/pt/subway-surfers/com.kiloo.subwaysurf/download/apk
> > 
> > 
> > Ótimo, agora que sabemos o tipo de jogo. Porém, apenas conhecer o tipo de jogo não é suficiente para identificar o problema. IDA mostra que a tabela de exportação exporta todas as funções necessárias; esta parte da questão foi descartada. Agora precisamos determinar quaisquer problemas relacionados ao código, como inicialização.
> 
> I initialized it like this, after il2cpp started the game closed
> 
> ![image](https://private-user-images.githubusercontent.com/163964035/314172024-2ecb98a8-d290-4bb4-a778-317bad6c9ecb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODA5OTAsIm5iZiI6MTcxMTA4MDY5MCwicGF0aCI6Ii8xNjM5NjQwMzUvMzE0MTcyMDI0LTJlY2I5OGE4LWQyOTAtNGJiNC1hNzc4LTMxN2JhZDZjOWVjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwNDExMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01Yjc0NGY4YjFlNGU5ODBmZWVlNzgzMGJkMzlmYWZhZTMxODEwMDFkYWQzZmQ4YTYzZGQ3NGM5ODMxZTFhNTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SA00mJevTmS-CR9DTcbkl1e0sew7709DXPFV2CpD4iE)

The code seems to have no issues. Without debugging information, it's difficult to pinpoint the problem.
